name: Android E2E Tests with Backend

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /opt/android-sdk
      API_LEVEL: 30
      EMULATOR_NAME: test-emulator

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Vision-Parking/tests/requirements.txt

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platform-tools system-images;android-30;google_apis;x86_64'

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Clean up Docker Compose (remove old containers and volumes)
      - name: Clean up Docker Compose
        run: docker-compose down -v
        working-directory: ./Backend

      # Start backend with Docker Compose
      - name: Start backend with Docker Compose
        run: docker-compose up -d
        working-directory: ./Backend

      # Wait for backend to be ready
      - name: Wait for backend to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:5000/health; then
              echo "Backend is up!"
              exit 0
            fi
            echo "Waiting for backend..."
            sleep 5
          done
          echo "Backend did not start in time"
          exit 1
        working-directory: ./Backend

      # --- Database migration steps ---
      - name: Initialize DB migration environment (if needed)
        run: docker-compose exec -T app flask db init || true
        working-directory: ./Backend

      # Stamp existing database state as up-to-date
      - name: Stamp existing database state as up-to-date
        run: docker-compose exec -T app flask db stamp head
        working-directory: ./Backend

      - name: Generate migration scripts
        run: docker-compose exec -T app flask db migrate -m "Initial migration"
        working-directory: ./Backend

      - name: Apply migrations to database
        run: docker-compose exec -T app flask db upgrade
        working-directory: ./Backend

      # Debug Android cmdline-tools
      - name: Debug Android cmdline-tools
        run: ls -l $ANDROID_HOME/cmdline-tools

      # Inject Google Maps API Key (before build)
      - name: Inject Google Maps API Key
        run: echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> Vision-Parking/local.properties

      # Run E2E tests on emulator
      - name: Run E2E tests on emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 5
          emulator-options: -no-window -no-audio -no-boot-anim -no-snapshot
          script: |
            cd Vision-Parking
            ./gradlew assembleDebug -p app
            $ANDROID_HOME/platform-tools/adb wait-for-device
            # Wait until emulator fully boots (returns "1")
            for i in {1..30}; do
              BOOT_STATUS=$($ANDROID_HOME/platform-tools/adb shell getprop sys.boot_completed | tr -d '\r')
              if [[ "$BOOT_STATUS" == "1" ]]; then
                echo "Emulator booted!"
                break
              fi
              echo "Waiting for emulator to boot..."
              sleep 5
            done
            $ANDROID_HOME/platform-tools/adb install -r app/build/outputs/apk/debug/app-debug.apk
            npm install -g appium
            nohup appium --log appium.log &
            sleep 15
            pytest --maxfail=1 --disable-warnings --html=tests/report.html --self-contained-html

      # Upload test report
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report
          path: Vision-Parking/tests/report.html

      # Upload Appium log
      - name: Upload Appium log
        uses: actions/upload-artifact@v4
        with:
          name: appium-log
          path: appium.log 
